package core.input;

public enum InputEvent {
    KEY_PRESSED,
    KEY_RELEASED,
    KEY_TYPED,
    MOUSE_CLICKED,
    MOUSE_DRAGGED,
    MOUSE_ENTERED,
    MOUSE_EXITED,
    MOUSE_MOVED,
    MOUSE_PRESSED,
    MOUSE_RELEASED,
    MOUSE_WHEEL_MOVED;
}
